SELECT*FROM employee
--UPDATE employee SET name = 'Bony' WHERE name = 'Sarah'
--UPDATE employee SET birthday='1996-11-18' WHERE id =2;
--UPDATE employee SET name ='XXX' WHERE name LIKE '%y'
--UPDATE employee SET name = 'Lottely' WHERE id = 8
--UPDATE employee SET name ='Dore' WHERE name LIKE '%s' 
--DELETE FROM employee WHERE id = 3
--DELETE FROM employee WHERE name LIKE '%k'
--DELETE FROM employee WHERE birthday = '1966-01-21'
--DELETE FROM employee WHERE name = 'Jeni'
--DELETE FROM employee  WHERE id = 23